name: Bug Report
description: Report something that isn't working right
labels: [bug]
body:
  - type: input
    id: version
    attributes:
      label: Extension Version
      description: What version of the Chromium Web Store extension are you using?
      placeholder: e.g. 1.0.0.0
    validations:
      required: true

  - type: textarea
    id: describe
    attributes:
      label: What happened?
      description: Describe the issue in detail, including steps to reproduce it.
      placeholder: A clear and concise description of the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: If applicable, tell us what you expected instead.
      placeholder: I expected it to...
  
  - type: textarea
    id: logs
    attributes:
      label: Console errors (if any)
      description: Paste any errors from the browser console here.
      render: shell

  - type: dropdown
    id: chromium_version
    attributes:
      label: Chromium Version
      description: What version of Chromium are you using?
    validations:
      required: true

  - type: textarea
    id: other_info
    attributes:
      label: Additional context
      description: Add any other information that might help us diagnose the problem.