name: 🐞 Bug Report
description: Report a problem with the Chromium Web Store extension
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! Please complete the fields below clearly and concisely.

  - type: input
    id: version
    attributes:
      label: Extension Version
      description: Which version/commit of the Chromium Web Store extension are you using?
      placeholder: e.g. 1.0.0.0
    validations:
      required: true

  - type: input
    id: chromium_version
    attributes:
      label: Chromium Version
      description: What version of Chromium or Ungoogled Chromium are you using?
      placeholder: e.g. 111.0.0.0 or the specific commit hash
    validations:
      required: true

  - type: textarea
    id: describe
    attributes:
      label: What happened?
      description: Describe the issue in detail, including steps to reproduce it.
      placeholder: A clear and concise description of the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: If applicable, tell us what you expected instead.
      placeholder: I expected it to...
  
  - type: textarea
    id: logs
    attributes:
      label: Console errors (if any)
      description: Paste any errors from the browser console here (use triple backticks).
      render: shell

  - type: textarea
    id: other_info
    attributes:
      label: Additional context
      description: Add any other information that might help us diagnose the problem.