name: ✨ Feature Request
description: Suggest a new idea or improvement
labels: [enhancement]
body:
  - type: input
    id: title
    attributes:
      label: Feature Title
      description: A short, descriptive title for your idea
      placeholder: e.g. Auto-update frequency setting
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: Describe the feature, how it works, and why it's useful.
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Why is this feature useful?
      description: Explain how this improves the extension or solves a problem.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: Have you tried workarounds or other ways to solve the problem?

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or links to related issues here.